--------------------4 LAB EDIT DETAILS TABLES-------------------
ALTER TABLE Project
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Project ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Project ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Customer
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Customer ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Customer ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Performer
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Performer ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Performer ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Project_Perforemers
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Project_Perforemers ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Project_Perforemers ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Customer_Bill
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Customer_Bill ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Customer_Bill ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Difficulty_Category
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Difficulty_Category ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Difficulty_Category ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Position
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Position ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Position ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Qualification
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Qualification ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Qualification ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Reports
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Reports ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Reports ALTER COLUMN ULC NVARCHAR(MAX);

ALTER TABLE Salary
ADD UCR TEXT,
    DCR DATETIME,
    ULC TEXT,
    DLC DATETIME;

ALTER TABLE Salary ALTER COLUMN UCR NVARCHAR(MAX);
ALTER TABLE Salary ALTER COLUMN ULC NVARCHAR(MAX);
